# Generated by Django 5.0.4 on 2024-05-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postos_coleta',
            new_name='PostosColeta',
        ),
    ]
